old-idea/config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'static_pages/index'
  root 'static_pages#index'

  resources :posts
  resources :projects
  resources :contacts, only: [:new, :create]

  get '*path'  => redirect('/')
end

old-idea/app/models/contact.rb
class Contact < MailForm::Base
  attribute :name, :validate => true
  attribute :email, :validate => /\A([\w\.%\+\-]+)@([\w\-\_]+\.)+([\w]{2,})\z/i
  attribute :message, :validate => true
  attribute :nickname, :captcha => true

  def headers
    {
      :subject => "Contact Form",
      :to => "emclaughlin1215@gmail.com",
      :from => %("#{name}" <#{email}>)
    }
  end
end

old-idea/app/models/post.rb
class Post < ApplicationRecord
  extend FriendlyId
  friendly_id :title, use: :slugged
end

old-idea/app/models/project.rb
class Project < ApplicationRecord
  extend FriendlyId
  friendly_id :title, use: :slugged
end

old-idea/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :recoverable, :rememberable, :validatable
end

old-idea/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  attr_accessor :hero_path, :title, :hero_heading, :hero_text, :hero_alignment
end

old-idea/app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def new
    @contact = Contact.new
  end

  def create
    @contact = Contact.new(params[:contact])
    @contact.request = request
    if @contact.deliver
      flash.now[:error] = nil
    else
      flash.now[:error] = 'Cannot send message.'
      render :new
    end
  end
end

old-idea/app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :find_post, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]

  def index
    @posts = Post.all.order('created_at desc').paginate(page: params[:page, per_page: 10])
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new post_params

    if @post.save
      redirect_to @post, notice: "Post created."
    else
      render 'new', notice: "Something went wrong."
    end
  end

  def show
  end

  def edit
  end

  def update
    if @post.update post_params
      redirect_to @post, notice: "Successful update."
    else
      render 'edit', notice: "something went wrong."
    end
  end

  def destroy
    @post.destroy
    redirect_to posts_path
  end

  private

    def post_params
      params.require(:post).permit(:title, :content, :slug)
    end

    def find_post
      @post = Post.friendly.find(params[:id])
    end
end

old-idea/app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :find_project, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]
  
  def index
    @projects = Project.all.order_by('created_at desc').paginate(page: params[:page, per_page: 10])
  end

  def new
    @project = Project.new
  end

  def create
    @project = Project.new project_params

    if @project.save
      redirect_to @project, notice: "Project created."
    else
      render 'new', notice: "Something went wrong."
    end
  end

  def show
  end

  def edit
  end

  def update
    if @project.update project_params
      redirect_to @project, notice: "Successful update."
    else
      render 'edit', notice: "something went wrong."
    end
  end

  def destroy
    @project.destroy
    redirect_to projects_path
  end

  private

    def project_params
      params.require(:project).permit(:title, :description, :link)
    end

    def find_project
      @project = Project.find(params[:id])
    end
end

old-idea/app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def index
  	@hero_path = '/heros/snow-1120800.jpg'
  	@hero_heading = "Erin McLaughlin"
  	@hero_text = "Certified Drupal and Rails Web Developer"
  	@hero_alignment = 'left'
    @posts = Post.all.limit(3).order("created_at desc")
    @projects = Project.all.limit(3).order("created_at desc")
  end
end

old-idea/app/helpers/application_helper.rb
module ApplicationHelper
  class HTMLwithPygments < Redcarpet::Render::HTML
    def block_code(code, language)
      Pygments.highlight(code, lexer: language)
    end
  end

  def markdown(content)
    renderer = HTMLwithPygments.new()
    options = {
      hard_wrap: true,
      filter_html: true,
      autolink: true,
      no_intra_emphasis: true,
      disable_indented_code_blocks: true,
      fenced_code_blocks: true,
      lax_html_blocks: true,
      strikethrough: true,
      superscript: true
    }
    Redcarpet::Markdown.new(renderer, options).render(content).html_safe
  end
end

old-idea/app/helpers/contacts_helper.rb
module ContactsHelper
end

old-idea/app/helpers/posts_helper.rb
module PostsHelper
end

old-idea/app/helpers/projects_helper.rb
module ProjectsHelper
end

old-idea/app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

old-idea/app/views/contacts/create.html.erb
<h1>Contact</h1>

<h2>Thank you for your message.</h2>
<p>I'll get back to you soon.</p>

old-idea/app/views/contacts/new.html.erb
<h1>Contact</h1>

<%= form_for @contact do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :email %>
  <%= f.email_field :email %>

  <%= f.label :message %>
  <%= f.text_area :email, as: :text %>

  <div class="hidden">
    <%= f.label :nickname %>
    <%= f.text_field :nickname, hint: 'leave this field blank' %>
  </div>

  <%= f.submit 'Send Message', class: 'button' %>

<% end %>

old-idea/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "Two is for Joy - Drupal and Rails Web Development" %></title>

    <link href="https://fonts.googleapis.com/css?family=Lato:400,400i,700,700i|Special+Elite" rel="stylesheet">

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "application", 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <header data-sticky-container role="banner" aria-label="Site Header">
      <div class="sticky is-at-top is-anchored header" data-sticky data-options="marginTop:0;">
        <div class="grid-container">
          <div class="grid-x">
            <div class="cell hide-for-small-only medium-4 header__personal">
              <a href="/" class="header__logo"><%= image_tag "logo.png" %></a>
              <span class="header__personal-name">Erin McLaughlin</span>
            </div>

            <div class="cell align-center text-center small-10 medium-4">
              <%= link_to "Two is for Joy", root_path, class: "header__site-name" %>
            </div>

            <div class="title-bar small-2 cell show-for-small-only" data-responsive-toggle="main-nav">
              <button class="menu-icon" type="button" data-toggle="main-nav"></button>
            </div>

            <div class="cell small-12 medium-4 align-right">
              <nav id="main-nav" data-animate="slide-in-down slide-out-up">
                <ul class="menu expanded align–center vertical medium-horizontal" data-dropdown-menu>
                  <li class="small-12 medium-4"><%= link_to "Blog", posts_path %></li>
                  <li class="small-12 medium-4"><%= link_to "Projects", projects_path %></li>
                  <li class="small-12 medium-4"><%= link_to "Contact", new_contact_path %></li>
                </ul>
              </nav>
            </div>
          </div>
        </div>
      </div>
    </header>

    <% if @hero_path %>
      <div class="hero expanded" style="background: url('<%= @hero_path %>') 50% no-repeat;">
        
        <% if @hero_heading or @hero_text %>
          <div class="hero__description">
            <% if @hero_heading %>
              <div class="hero__title">
                <h1><%= @hero_heading %></h1>
              </div>
            <% end %>
            <% if @hero_text %>
              <div class="hero__text">
                <h3><%= @hero_text %></h3>
              </div>
            <% end %>
          </div>
        <% end %>
      </div>
    <% end %>

    <main class="grid-container" role="main">
      <%= yield %>
    </main>

    <footer class="small-11 medium-10" role="footer">
      <% if user_signed_in? %>
        <%= link_to "Log Out", destroy_user_session_path %>
        <%= link_to "New Post", new_post_path %>
        <%= link_to "New Project", new_project_path %>
      <% end %>
    </footer>

  </body>
</html>

old-idea/app/views/posts/_disqus.html.erb
<div id="disqus_thread"></div>
<script>

/**
*  RECOMMENDED CONFIGURATION VARIABLES: EDIT AND UNCOMMENT THE SECTION BELOW TO INSERT DYNAMIC VALUES FROM YOUR PLATFORM OR CMS.
*  LEARN WHY DEFINING THESE VARIABLES IS IMPORTANT: https://disqus.com/admin/universalcode/#configuration-variables
*/

var disqus_config = function () {
this.page.url = '<%= post_url(@post) %>';  // Replace PAGE_URL with your page's canonical URL variable
this.page.identifier = '<%= @post.id %>'; // Replace PAGE_IDENTIFIER with your page's unique identifier variable
this.page.title = '<%= @post.title %>';
};

(function() { // DON'T EDIT BELOW THIS LINE
var d = document, s = d.createElement('script');
s.src = 'https://two-is-for-joy.disqus.com/embed.js';
s.setAttribute('data-timestamp', +new Date());
(d.head || d.body).appendChild(s);
})();
</script>
<noscript>Please enable JavaScript to view the <a href="https://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>

old-idea/app/views/posts/_form.html.erb
<%= form_for @post do |f| %>
  <% if @post.errors.any? %>
    <h2><%= pluralize(@post.errors.count, "error", "errors") %> prevented this post from saving:</h2>
    <ul>
      <%= @post.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  <% end %>

  <%= f.label :title %>
  <%= f.text_field :title %>

  <%= f.label :content %>
  <%= f.text_area :content %>

  <%= f.submit %>
<% end %>

old-idea/app/views/posts/edit.html.erb
<h1>Edit Post</h1>

<%= render 'form' %>

old-idea/app/views/posts/index.html.erb
<h1>Stuff What's Written</h1>

<% @posts.each do |post| %>
  <%= post.created_at.strftime('%A, %b %d') %>
  <%= link_to post.title, post %>
<% end %>

<%= will_paginate @posts %>

old-idea/app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form' %>

old-idea/app/views/posts/show.html.erb
<h1><%= @post.title %></h1>
<%= @post.created_at.strftime("%A, %b %d") %>

<%= markdown @post.content %>

<% if user_signed_in? %>
	<%= link_to "Edit", edit_post_path(@post) %>
	<%= link_to "Delete", post_path(@post), method: :delete, data: { confirm: "Are you sure you want to delete this post?" } %>
<% end %>

<%= render 'disqus' %>

old-idea/app/views/projects/_form.html.erb
<%= form_for @project do |f| %>
  <% if @project.errors.any? %>
    <h2><%= pluralize(@project.errors.count, "error", "errors") %> prevented this project from saving:</h2>
    <ul>
      <%= @project.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  <% end %>

  <%= f.label :title %>
  <%= f.text_field :title %>

  <%= f.label :content %>
  <%= f.text_area :content %>

  <%= f.label :link %>
  <%= f.text_field :link %>

  <%= f.submit %>
<% end %>

old-idea/app/views/projects/edit.html.erb
<h1>Edit Project</h1>

<%= render 'form' %>

old-idea/app/views/projects/index.html.erb
<h1>Stuff What's Built</h1>

<% @projects.each do |project| %>
  <%= project.created_at.strftime('%A, %b %d') %>
  <%= link_to project.title, project %>
<% end %>

<%= will_paginate @posts %>

old-idea/app/views/projects/new.html.erb
<h1>New Project</h1>

<%= render 'form' %>

old-idea/app/views/projects/show.html.erb
<h1><%= @project.title %></h1>
<%= @project.created_at.strftime("%A, %b %d") %>

<%= markdown @project.content %>

<a href="<%= @project.link %>">See <%= @project.title %> Live</a>

<% if user_signed_in? %>
	<%= link_to "Edit", edit_project_path(@project) %>
	<%= link_to "Delete", project_path(@project), method: :delete, data: { confirm: "Are you sure you want to delete this project?" } %>
<% end %>

old-idea/app/views/static_pages/index.html.erb
<div class="wrapper">
  <div class="about">
    <h2>About Me</h2>
    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce sollicitudin ligula sed odio pulvinar porttitor. Praesent et odio urna. Sed porta orci eu ante porttitor, in viverra lectus consectetur. Maecenas vitae libero purus. Curabitur faucibus faucibus sapien vulputate tincidunt. Suspendisse fringilla vel lectus non mattis. Interdum et malesuada fames ac ante ipsum primis in faucibus.

Curabitur et odio ante. Proin tempor cursus sollicitudin. Mauris pharetra neque in justo feugiat, vitae malesuada enim efficitur. Curabitur et odio arcu. Nullam auctor pharetra consequat. Vivamus accumsan sit amet diam ac lobortis. Donec fermentum magna sit amet metus hendrerit accumsan. Donec pharetra enim ac magna faucibus, eget porttitor nibh laoreet. Nulla tellus quam, mattis id sagittis id, auctor vel dui. Nunc quis tincidunt ligula, et malesuada magna.

Vestibulum efficitur eros sit amet augue ornare aliquet quis vitae diam. Donec volutpat viverra lorem. Quisque id augue ullamcorper, laoreet ante sed, venenatis nulla. Duis leo mauris, eleifend eget vulputate quis, dapibus id lorem. Suspendisse blandit felis erat, vitae ultrices enim eleifend id. Duis rhoncus, felis vel maximus aliquet, turpis urna placerat tortor, sed luctus justo mi non ante. Praesent pulvinar tincidunt lorem volutpat tincidunt. Cras pharetra euismod odio efficitur mollis. Fusce vestibulum eleifend eros, sit amet congue diam euismod eu. Etiam fermentum, tortor in tempus auctor, turpis neque tincidunt risus, at vulputate justo eros sit amet elit. Sed et nisi eros. Lorem ipsum dolor sit amet, consectetur adipiscing elit.

Quisque a ante ac dui consequat ornare id quis sapien. Mauris nisl sapien, aliquam vel mi nec, malesuada condimentum urna. Vivamus consequat odio nec nulla maximus auctor. Proin tincidunt sem sapien, et ultrices magna euismod sit amet. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Suspendisse tempus iaculis lorem, eget semper ligula pellentesque non. Sed eu finibus sem. Proin aliquet ultrices posuere. Pellentesque semper viverra laoreet. In mi neque, aliquet sed pharetra eget, pulvinar nec leo. Mauris magna nulla, consequat nec laoreet sed, aliquam sed neque. Pellentesque at est scelerisque, tincidunt leo rhoncus, elementum elit. Fusce cursus, nisl a ornare luctus, mauris mauris condimentum dolor, ut luctus erat libero vel ipsum. Morbi aliquam nisi ut sagittis ultricies.

Donec vel urna volutpat, accumsan leo vitae, eleifend nibh. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Sed ex ex, cursus et eros in, pretium eleifend odio. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Cras volutpat nec lectus at laoreet. Sed aliquet urna eget tellus venenatis vestibulum. Curabitur blandit vulputate orci, vel ultricies ante aliquam eu. Vivamus enim tortor, pellentesque nec ipsum id, bibendum venenatis lectus.

Nulla facilisi. Vestibulum fermentum sodales ultricies. Cras quis lectus sollicitudin, dapibus justo vitae, fringilla nunc. Donec tempor feugiat mi, in congue turpis vehicula sed. Mauris a dignissim ipsum. Donec ac elit at tellus dapibus euismod eget at mi. Nullam metus dui, bibendum nec lacus vel, sollicitudin commodo magna. In auctor, urna non cursus accumsan, magna velit maximus dui, et venenatis justo turpis sed elit. Praesent ut eros non orci ullamcorper eleifend venenatis ac quam. Vivamus cursus dolor non orci gravida vestibulum. Etiam faucibus scelerisque faucibus. Integer et gravida lacus, ut posuere felis. Ut a mauris id orci condimentum dapibus.

Vestibulum nibh sem, varius quis porta sed, maximus quis nisi. Vivamus eu vehicula justo, sed vehicula nisi. Pellentesque a augue ut erat gravida auctor. Donec eu accumsan elit. Vivamus id sodales diam. Etiam vulputate facilisis tellus sed rutrum. In hac habitasse platea dictumst. Proin vehicula, magna a eleifend accumsan, leo lorem aliquam enim, vitae sodales quam tortor ac odio. In eu ligula in risus hendrerit interdum. Phasellus dignissim lacus ac turpis lacinia sodales. Nam et velit urna. Praesent eget mauris interdum massa sodales convallis.

Phasellus nec nibh id mauris vestibulum tristique quis nec tortor. Mauris dui ligula, fermentum non tincidunt eget, sodales quis quam. Aliquam erat volutpat. Fusce pellentesque, justo vel faucibus condimentum, justo orci dapibus neque, vitae ultricies tellus eros at purus. Nullam rutrum tincidunt sapien vitae finibus. Etiam eget neque semper, hendrerit lorem eget, scelerisque lorem. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Praesent fringilla eget orci vel pellentesque. Aliquam eleifend justo ut enim imperdiet, sed porttitor dui euismod.

Nulla iaculis ac dolor id efficitur. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Ut neque velit, tincidunt quis condimentum sit amet, sagittis eu risus. Donec at elit sit amet tellus commodo auctor ac porttitor sem. Vestibulum eu interdum erat. Cras justo ante, lobortis ut dolor dignissim, laoreet lobortis sapien. Nullam accumsan tellus vitae est posuere tempor. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum rhoncus, ligula ut imperdiet venenatis, lectus velit sodales augue, eget auctor nulla libero at risus. Duis turpis dui, malesuada eu dapibus eget, pellentesque vel libero. Suspendisse feugiat felis neque, sed varius quam aliquam et. Pellentesque sit amet bibendum risus.

Vivamus dictum tortor ut augue tempus suscipit. Praesent mattis molestie ligula sed mollis. Morbi pellentesque blandit nunc sed sodales. Sed eu tempor ante, sed vulputate elit. Nulla tristique molestie tortor. Mauris ornare eleifend nibh, nec porttitor tellus blandit non. Suspendisse et consectetur lacus. Donec auctor tortor id condimentum dictum. Sed vel feugiat turpis, cursus pellentesque mauris. Curabitur eu egestas lectus. Etiam sit amet turpis elit. Nullam posuere non purus sit amet fermentum.

Duis finibus, erat vitae suscipit dapibus, odio est eleifend nulla, at fringilla purus libero non tortor. Mauris dui elit, consectetur eget rutrum quis, mattis eu eros. Nam justo risus, viverra ac dui nec, sollicitudin bibendum ante. Sed elementum, metus ut rhoncus elementum, turpis purus rhoncus risus, id rutrum est nunc at purus. Fusce iaculis, neque vel porttitor pulvinar, tellus purus semper leo, sit amet pretium dolor nisl ac augue. Vivamus eu ligula nulla. Morbi convallis, elit rutrum euismod scelerisque, lacus dui tincidunt purus, vel aliquam diam risus vel magna. Etiam tristique dignissim orci in interdum. Sed vitae sem in leo euismod interdum. Quisque pulvinar purus ex, quis condimentum odio fringilla eget. Quisque id augue id dui venenatis fringilla. Donec convallis augue ornare laoreet interdum. Aliquam erat volutpat. Aenean volutpat elit leo, a rhoncus libero aliquet id. Sed feugiat elit nec est volutpat lobortis.

Vestibulum et quam pharetra, aliquet ligula vitae, egestas libero. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Aliquam sit amet nisi vel mauris mollis maximus in dictum nisi. In maximus nulla sed elit porta eleifend. Maecenas accumsan pellentesque nulla vel cursus. Mauris at ante tellus. Aenean nunc elit, commodo nec mattis a, varius rhoncus magna. Praesent in malesuada nunc, id lobortis dolor. Sed lorem libero, porttitor quis posuere a, vestibulum at massa. Suspendisse potenti. Donec sed ultricies urna. Sed quis ante dolor. Aliquam erat volutpat. In facilisis consectetur ullamcorper. Sed gravida sodales risus, ut mattis augue viverra non.

Praesent eu convallis leo. Suspendisse aliquet eget odio rhoncus tempus. Fusce vitae ex mattis, imperdiet magna vitae, aliquam dolor. Maecenas faucibus vitae lorem in pretium. Aenean commodo tincidunt diam, eu tincidunt sapien aliquet non. Etiam vitae ultrices lacus. Nam odio diam, pellentesque quis porta pulvinar, tristique sed lacus. Quisque auctor suscipit rhoncus. Aenean posuere ultrices pulvinar. Sed commodo lorem massa, eget mattis turpis blandit sodales.

Praesent sit amet lacinia ligula. Maecenas hendrerit urna sed fermentum porta. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Quisque eu lacus elit. Nulla facilisi. Curabitur at tellus erat. Praesent vel lorem nec velit bibendum posuere in quis massa. Vivamus eget ultricies velit, a posuere mauris. Sed dapibus eu lectus a sodales. Duis consequat imperdiet nibh sit amet vulputate.

Integer nisl erat, tempus in iaculis quis, auctor ac dolor. Aenean velit mauris, maximus ac placerat ut, convallis vitae lectus. Ut ac mollis tortor. Etiam dignissim vestibulum efficitur. Cras neque ex, pharetra sit amet accumsan vel, lobortis non ante. Suspendisse potenti. Maecenas ultrices elit et rhoncus posuere. Suspendisse ac tristique lorem. Pellentesque et lorem sem. Aenean a quam molestie, sagittis odio id, ullamcorper libero.
  </div>
  <div class="blog_posts">
    <% @posts.each do |post| %>
      <h3><a href="#"><%= link_to post.title, post %></a></h3>
      <p class="date"><%= post.created_at.strftime("%A, %b %d") %></p>
    <% end %>
  </div>

  <div class="projects">
    <% @projects.each do |project| %>
      <h3><a href="#"><%= link_to project.title, project %></a></h3>
      <p class="date"><%= project.created_at.strftime("%A, %b %d") %></p>
    <% end %>
  </div>
</div>